### ISSUE TITLE
master missing build directory contents

### ISSUE THREAD

**Issue by Sabine-Schnabeltier** [mlba-team/xdispatch#5]
The master branch appears to have a placeholder for the build directory rather than the directory and its contents.

Using the build directory from the stable branch almost works, but cmake stops due to a missing definition for "mz_auto_format".

**Comment by emzeat** [comment]
Sabine,

The build directory on the master branch is a submodule that needs to be pulled first. You will need to do a local clone of the repository and execute `git submodule update —init` from within your cloned repository.

Regards,
Marius

**Comment by Sabine-Schnabeltier** [comment]
Hi Marius,

Thanks for the quick response. I tried what you suggested but got an error:

fatal: repository 'https://github.com/mlba-team/mz-cmaketools.git/' not
found


Is the URL for the submodule correct?

Thanks for your help!

Sabine

**Comment by emzeat** [comment]
Sorry for that, said repository had not been mirrored yet. I should all be working now.

**Comment by Sabine-Schnabeltier** [comment]
Thank you, it is working now!
